# Generated by Django 5.2.7 on 2025-10-31 17:15

import datetime
import django.core.validators
import django.db.models.deletion
import django_cpf_cnpj.fields
import toolcare_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=255, unique=True)),
                ('descricao_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=255, unique=True)),
                ('descricao_setor', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, default='defaults/default_ferramenta.png', upload_to=toolcare_api.models.upload_path_ferramenta)),
                ('data_aquisicao', models.DateField()),
                ('estado', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EMPRESTADA', 'Emprestada'), ('EM_MANUTENCAO', 'Em Manutenção'), ('INATIVA', 'Inativa')], default='DISPONIVEL', max_length=20)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='toolcare_api.deposito')),
            ],
        ),
        migrations.AddField(
            model_name='deposito',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='toolcare_api.filial'),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Somente números são permitidos.')])),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14, unique=True)),
                ('foto', models.ImageField(blank=True, default='defaults/default_avatar.png', upload_to=toolcare_api.models.upload_path_funcionario)),
                ('ativo', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolcare_api.cargo')),
                ('filiais', models.ManyToManyField(related_name='funcionarios', to='toolcare_api.filial')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolcare_api.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(default=datetime.date.today)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome_ferramenta_historico', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_serie_ferramenta_historico', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_funcionario_historico', models.CharField(blank=True, max_length=100, null=True)),
                ('matricula_funcionario_historico', models.CharField(blank=True, max_length=50, null=True)),
                ('ferramenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolcare_api.ferramenta')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolcare_api.funcionario')),
            ],
        ),
    ]
