# Generated by Django 5.2.7 on 2025-10-02 14:54

import django.core.validators
import django.db.models.deletion
import django_cpf_cnpj.fields
import toolcare_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=255)),
                ('descricao_cargo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=255)),
                ('descricao_setor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Somente números são permitidos.')])),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=toolcare_api.models.upload_path_funcionario)),
                ('ativo', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolcare_api.cargo')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolcare_api.setor')),
            ],
        ),
    ]
