# Generated by Django 5.2.7 on 2025-11-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolcare_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_active',
            new_name='ativo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('MAXIMO', 'Máximo'), ('ADMINISTRADOR', 'Administrador'), ('COORDENADOR', 'Coordenador')], max_length=15),
        ),
    ]
