# Generated by Django 5.2.7 on 2025-10-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolcare_api', '0002_deposito_ativo_filial_ativo_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
