# Generated by Django 5.2.7 on 2025-12-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolcare_api', '0002_rename_is_active_usuario_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
