# Generated by Django 5.2.7 on 2025-10-02 15:19

import toolcare_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolcare_api', '0002_alter_funcionario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, default='defaults/default_funcionario.png', upload_to=toolcare_api.models.upload_path_funcionario),
        ),
    ]
