# Generated by Django 5.2.7 on 2025-12-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolcare_api', '0003_manutencao_observacoes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deposito',
            constraint=models.UniqueConstraint(fields=('nome', 'filial'), name='unique_nome_por_filial'),
        ),
    ]
