# Generated by Django 5.2.7 on 2025-10-09 13:23

import datetime
import django.db.models.deletion
import toolcare_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolcare_api', '0003_alter_funcionario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=toolcare_api.models.upload_path_ferramenta)),
                ('data_aquisicao', models.DateField()),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em Uso'), ('EM_MANUTENCAO', 'Em Manutenção'), ('DESATIVADA', 'Desativada')], default='DISPONIVEL', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, default='defaults/default_avatar.png', upload_to=toolcare_api.models.upload_path_funcionario),
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(default=datetime.date.today)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolcare_api.funcionario')),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolcare_api.ferramenta')),
            ],
        ),
    ]
