# Generated by Django 5.2.7 on 2025-10-09 14:21

import toolcare_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolcare_api', '0004_ferramenta_alter_funcionario_foto_emprestimo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='ativo',
            new_name='estado',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='status',
        ),
        migrations.AddField(
            model_name='cargo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='estado',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EMPRESTADA', 'Emprestada'), ('EM_MANUTENCAO', 'Em Manutenção'), ('INATIVA', 'Inativa')], default='DISPONIVEL', max_length=20),
        ),
        migrations.AddField(
            model_name='setor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='foto',
            field=models.ImageField(blank=True, default='defaults/default_ferramenta.png', upload_to=toolcare_api.models.upload_path_ferramenta),
        ),
    ]
