# Generated by Django 5.2.7 on 2025-12-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolcare_api', '0004_deposito_unique_nome_por_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramenta',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
