# Generated by Django 5.2.7 on 2025-10-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolcare_api', '0005_rename_ativo_funcionario_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nome_cargo',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome_setor',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
