# Generated by Django 5.2.7 on 2025-10-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolcare_api', '0006_alter_cargo_nome_cargo_alter_setor_nome_setor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='estado',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='emprestimo',
            old_name='estado',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='estado',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='setor',
            old_name='estado',
            new_name='ativo',
        ),
    ]
