# Generated by Django 5.2.7 on 2025-10-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolcare_api', '0008_emprestimo_nome_ferramenta_historico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='matricula_funcionario_historico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='numero_serie_ferramenta_historico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
